### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by gursheyss** [SCE-Development/sjsu-rmp#8]
We're going to implement authentication with [Lucia](https://lucia-auth.com/getting-started/sveltekit)
also https://arctic.js.org/providers/google

- [ ] Create tables for auth
- [ ] Setup drizzle driver with Lucia
- [ ] Setup google oauth (once u get the part where u need secrets just dm me for them)
- [ ] Create components for sign in and sign out (just keep them on the home page as buttons until we move them to a header)

This will require you to google and read thru documentation, but feel free to dm me if you're stuck anywhere

**Comment by jonathanguven** [comment]
sup
